var userdatagrid;
$(function(){
	
     userdatagrid=$("#usermanager").datagrid({
     title:'会员管理',
     url:getRequestPath('/user/useraction!getDatagrid'),
     fit:true,
     loadMsg:'数据加载中……',
     fitColumns:true,
     pagination:true,
     pageSize:5,
     pageList:[5,10,15,20,25,30],
     idField:'userId',
     striped:true,
     frozenColumns:[[
     	 {
     	 	field:'',
     	 	title:'全选',
     	 	checkbox:true
     	 },
         {
     		field:'userId',
     		title:'ID',
     		hidden:true
     	},
     	{
     		field:'username',
     		title:'用户名',
     		width:100
     	}
     ]],
     columns:[[
     	{
     		field:'password',
     		title:'密码',
     		width:100
     	},
     	{
     		field:'registertime',
     		title:'注册时间',
     		width:100
     	},
     	{
     		field:'address',
     		title:'所在地',
     		width:100
     	},
     	{
     		field:'phone',
     		title:'联系方式',
     		width:100
     	}
       ]],
     	toolbar:[
     		{
     		text:'修改',
     		iconCls:'icon-edit',
     		handler:function(){
     		    alert("修改");
     		}
     		},'-',
     		{
     		text:'删除',
     		iconCls:'icon-remove',
     		handler:function(){
     		   deleteData();
     		}
     		},'-',
     	    {
     	    text:'添加',
     	    iconCls:'icon-add',
     	    handler:function(){
     	     alert("添加");
     	    }
     	    }]
 });
});
function deleteData(){
   var Ids=[];
   var rows=userdatagrid.datagrid('getSelections');
   if(rows.length>0){
       $.messager.confirm("警告","是否真的要删除选中的行？",function(del){
          if(del){
            for(var i=0;i<rows.length;i++){
              Ids.push(rows[i].userId);
            }
            var userIds=Ids.join(',');
            console.info(userIds);
            $.ajax({
                type:'post',
                url:getRequestPath('/user/useraction!removeuserData'),
                data:{userIds:userIds}, 
                async:true,
                //datatype:'json',
                success:function(data){
                   var obj=jQuery.parseJSON(data);
                   if(obj.success){
                   	userdatagrid.datagrid('load');
                   	$.messager.show({title:"提示",msg:obj.msg});
                   }else{
                     $.messager.show({title:"提示",msg:obj.msg});
                   }
                }
            });
          }
       });
   }else{
   	  $.messager.alert("提示","请选择要删除的行！","warning");
   }
}
