window['PP.shop.baoyou.time'] && window['PP.shop.baoyou.time'].push(new Date());
function $addClass(ids,cName){$setClass(ids,cName,"add");};function $addEvent(obj,type,handle){if(!obj||!type||!handle){return;}
if(obj instanceof Array){for(var i=0,l=obj.length;i<l;i++){$addEvent(obj[i],type,handle);}
return;}
if(type instanceof Array){for(var i=0,l=type.length;i<l;i++){$addEvent(obj,type[i],handle);}
return;}
window.__allHandlers=window.__allHandlers||{};window.__Hcounter=window.__Hcounter||1;function setHandler(obj,type,handler,wrapper){obj.__hids=obj.__hids||[];var hid='h'+window.__Hcounter++;obj.__hids.push(hid);window.__allHandlers[hid]={type:type,handler:handler,wrapper:wrapper}}
function createDelegate(handle,context){return function(){return handle.apply(context,arguments);};}
if(window.addEventListener){var wrapper=createDelegate(handle,obj);setHandler(obj,type,handle,wrapper)
obj.addEventListener(type,wrapper,false);}
else if(window.attachEvent){var wrapper=createDelegate(handle,obj);setHandler(obj,type,handle,wrapper)
obj.attachEvent("on"+type,wrapper);}
else{obj["on"+type]=handle;}};function $addToken(url,type,skey){var token=$getToken(skey);if(url==""||(url.indexOf("://")<0?location.href:url).indexOf("http")!=0){return url;}
if(url.indexOf("#")!=-1){var f1=url.match(/\?.+\#/);if(f1){var t=f1[0].split("#"),newPara=[t[0],"&g_tk=",token,"&g_ty=",type,"#",t[1]].join("");return url.replace(f1[0],newPara);}else{var t=url.split("#");return[t[0],"?g_tk=",token,"&g_ty=",type,"#",t[1]].join("");}}
return token==""?(url+(url.indexOf("?")!=-1?"&":"?")+"g_ty="+type):(url+(url.indexOf("?")!=-1?"&":"?")+"g_tk="+token+"&g_ty="+type);};function $child(node,val,fn,filter){var results=[],filter=filter||$empty();if(!node)return results;walk(node.firstChild,function(n){if(!n){return;}
var actual=n.nodeType===1&&n.nodeName.toLowerCase();if(typeof actual==='string'&&(actual===val||typeof val!=='string')&&filter(n)){results.push(n);fn&&fn(n,results.length-1);}});return results;function walk(n,func){func(n);while(n&&(n=n.nextSibling)){func(n,func);}}};function $delClass(ids,cName){$setClass(ids,cName,"remove");};function $empty(){return function(){return true;}};(function(){var _formatJson_cache={};$formatJson=function(str,data){var fn=!/\W/.test(str)?_formatJson_cache[str]=_formatJson_cache[str]||$formatJson($id(str).innerHTML):new Function("obj","var p=[],print=function(){p.push.apply(p,arguments);};"+"with(obj){p.push('"+str.replace(/[\r\t\n]/g," ").split("<%").join("\t").replace(/((^|%>)[^\t]*)'/g,"$1\r").replace(/\t=(.*?)%>/g,"',$1,'").split("\t").join("');").split("%>").join("p.push('").split("\r").join("\\'")+"');}return p.join('');");return data?fn(data):fn;}})();function $getCookie(name){var reg=new RegExp("(^| )"+name+"(?:=([^;]*))?(;|$)"),val=document.cookie.match(reg);return val?(val[2]?unescape(val[2]):""):null;};function $getQuery(name,url){var u=arguments[1]||window.location.search,reg=new RegExp("(^|&)"+name+"=([^&]*)(&|$)"),r=u.substr(u.indexOf("\?")+1).match(reg);return r!=null?r[2]:"";};function $getTarget(e,parent,tag){var e=window.event||e,tar=e.srcElement||e.target;if(parent&&tag&&tar.nodeName.toLowerCase()!=tag){while(tar=tar.parentNode){if(tar==parent||tar==document.body||tar==document){return null;}else if(tar.nodeName.toLowerCase()==tag){break;}}};return tar;};function $getToken(skey){var skey=skey?skey:$getCookie("skey");return skey?$time33(skey):"";};function $hasClass(old,cur){if(!old||!cur)return null;var arr=(typeof old=='object'?old.className:old).split(' ');for(var i=0,len=arr.length;i<len;i++){if(cur==arr[i]){return cur;}};return null;};function $id(id){return typeof(id)=="string"?document.getElementById(id):id;};function $inArray(t,arr){if(arr.indexOf){return arr.indexOf(t);}
for(var i=arr.length;i--;){if(arr[i]===t){return i*1;}};return-1;};function $loadImg(obj,attr){if(!obj)return;var attr=attr||"back_src",images=obj.getElementsByTagName("IMG");for(var i=0,len=images.length;i<len;i++){var oImg=images[i],src=oImg.getAttribute(attr);''==oImg.src&&src&&(oImg.src=src);}};function $loadScript(obj){if(!$loadScript.counter){$loadScript.counter=1;}
var isObj=typeof(obj)=="object",url=isObj?obj.url:arguments[0],id=isObj?obj.id:arguments[1],obj=isObj?obj:arguments[2],_head=document.head||document.getElementsByTagName("head")[0]||document.documentElement,_script=document.createElement("script"),D=new Date(),_time=D.getTime(),_isCleared=false,_timer=null,o=obj||{},data=o.data||'',charset=o.charset||"gb2312",isToken=o.isToken,skey=o.skey,timeout=o.timeout,isAutoReport=o.isAutoReport||false,reportOptions=o.reportOptions||{},reportType=o.reportType||'current',reportRetCodeName=o.reportRetCodeName,reportSuccessCode=typeof(o.reportSuccessCode)=="undefined"?200:o.reportSuccessCode,reportErrorCode=typeof(o.reportErrorCode)=="undefined"?500:o.reportErrorCode,reportTimeoutCode=typeof(o.reportTimeoutCode)=="undefined"?600:o.reportTimeoutCode,onload=o.onload,onsucc=o.onsucc,callbackName=o.callbackName||'',callback=o.callback,errorback=o.errorback,_jsonpLoadState='uninitialized';var complete=function(errCode){if(!_script||_isCleared){return;}
_isCleared=true;if(_timer){clearTimeout(_timer);_timer=null;}
_script.onload=_script.onreadystatechange=_script.onerror=null;if(_head&&_script.parentNode){_head.removeChild(_script);}
_script=null;if(callbackName){if(callbackName.indexOf('.')==-1){window[callbackName]=null;try{delete window[callbackName];}
catch(e){}}
else{var arrJ=callbackName.split("."),p={};for(var j=0,jLen=arrJ.length;j<jLen;j++){var n=arrJ[j];if(j==0){p=window[n];}
else{if(j==jLen-1){try{delete p[n];}
catch(e){}}
else{p=p[n];}}}}}
if(_jsonpLoadState!="loaded"&&typeof errorback=="function"){errorback(errCode);}
if(isAutoReport&&reportType!='cross'){_retCoder.report(_jsonpLoadState=="loaded",errCode);}};var jsontostr=function(d){var a=[];for(var k in d){a.push(k+'='+d[k]);}
return a.join('&');};if(isAutoReport&&reportOptions){if(reportType=='cross'){$returnCode(reportOptions).reg();}
else{reportOptions.url=reportOptions.url||url.substr(0,url.indexOf('?')==-1?url.length:url.indexOf('?'));var _retCoder=$returnCode(reportOptions);}}
if(data){url+=(url.indexOf("?")!=-1?"&":"?")+(typeof data=='string'?data:jsontostr(data));}
if(callbackName&&typeof callback=="function"){var oldName=callbackName;if(callbackName.indexOf('.')==-1){callbackName=window[callbackName]?callbackName+$loadScript.counter++:callbackName;window[callbackName]=function(jsonData){_jsonpLoadState='loaded';if(isAutoReport&&reportRetCodeName){reportSuccessCode=jsonData[reportRetCodeName];}
callback.apply(null,arguments);onsucc&&(onsucc());};}
else{var arrJ=callbackName.split("."),p={},arrF=[];for(var j=0,jLen=arrJ.length;j<jLen;j++){var n=arrJ[j];if(j==0){p=window[n];}
else{if(j==jLen-1){p[n]?(n=n+$loadScript.counter++):'';p[n]=function(jsonData){_jsonpLoadState='loaded';if(isAutoReport&&reportRetCodeName){reportSuccessCode=jsonData[reportRetCodeName];}
callback.apply(null,arguments);onsucc&&(onsucc());};}
else{p=p[n];}}
arrF.push(n);}
callbackName=arrF.join('.');}
url=url.replace('='+oldName,'='+callbackName);}
_jsonpLoadState='loading';id=id?(id+_time):_time;url=(isToken!==false?$addToken(url,"ls",skey):url);_script.charset=charset;_script.id=id;_script.onload=_script.onreadystatechange=function(){var uA=navigator.userAgent.toLowerCase();if(!(!(uA.indexOf("opera")!=-1)&&uA.indexOf("msie")!=-1)||/loaded|complete/i.test(this.readyState)){if(typeof onload=="function"){onload();}
complete(_jsonpLoadState=="loaded"?reportSuccessCode:reportErrorCode);}};_script.onerror=function(){complete(reportErrorCode);};if(timeout){_timer=setTimeout(function(){complete(reportTimeoutCode);},parseInt(timeout,10));}
setTimeout(function(){_script.src=url;try{_head.insertBefore(_script,_head.lastChild);}catch(e){}},0);};function $loadUrl(o){o.element=o.element||'script';var el=document.createElement(o.element);el.charset=o.charset||'utf-8';o.onBeforeSend&&o.onBeforeSend(el);el.onload=el.onreadystatechange=function(){if(/loaded|complete/i.test(this.readyState)||navigator.userAgent.toLowerCase().indexOf("msie")==-1){o.onLoad&&o.onLoad();clear();}};el.onerror=function(){clear();};el.src=o.url;document.getElementsByTagName('head')[0].appendChild(el);function clear(){if(!el){return;}
el.onload=el.onreadystatechange=el.onerror=null;el.parentNode&&(el.parentNode.removeChild(el));el=null;}};function $namespace(name){for(var arr=name.split(','),r=0,len=arr.length;r<len;r++){for(var i=0,k,name=arr[r].split('.'),parent={};k=name[i];i++){i===0?eval('(typeof '+k+')==="undefined"?('+k+'={}):"";parent='+k):(parent=parent[k]=parent[k]||{});}}};function $preventDefault(e){if(e&&e.preventDefault){e.preventDefault();}else{window.event.returnValue=false;};return false;};function $randomInt(num1,num2){if(num2==undefined){num2=num1;num1=0;}
return Math.floor(Math.random()*(num2-num1)+num1);};function $report(url){$loadUrl({'url':url+((url.indexOf('?')==-1)?'?':'&')+Math.random(),'element':'img'});};function $returnCode(opt){var option={url:"",action:"",sTime:"",eTime:"",retCode:"",errCode:"",frequence:1,refer:"",uin:"",domain:"paipai.com",from:1,report:report,isReport:false,timeout:3000,timeoutCode:444,formatUrl:true,reg:reg};try{option['refer']=location.href;}catch(e){}
for(var i in opt){option[i]=opt[i];}
if(option.url){option.sTime=new Date();}
if(option.timeout){setTimeout(function(){if(!option.isReport){option.report(false,option.timeoutCode);}},option.timeout);}
function reg(){this.sTime=new Date();if(!this.action){return;}
var rcookie=$getCookie("retcode"),cookie2=[];rcookie=rcookie?rcookie.split("|"):[];for(var i=0;i<rcookie.length;i++){if(rcookie[i].split(",")[0]!=this.action){cookie2.push(rcookie[i]);}}
cookie2.push(this.action+","+this.sTime.getTime());$setCookie("retcode",cookie2.join("|"),60,"/",this.domain);}
function report(ret,errid){if(this.isReport==true){return;}
this.isReport=true;this.eTime=new Date();this.retCode=ret?1:2;this.errCode=isNaN(parseInt(errid))?"0":parseInt(errid);if(this.action){this.url="http://retcode.paipai.com/"+this.action;var rcookie=$getCookie("retcode"),ret="",ncookie=[];rcookie=rcookie?rcookie.split("|"):[];for(var i=0;i<rcookie.length;i++){if(rcookie[i].split(",")[0]==this.action){ret=rcookie[i].split(",");}
else{ncookie.push(rcookie[i]);}}
$setCookie("retcode",ncookie.join("|"),60,"/",this.domain);if(!ret){return;}
this.sTime=new Date(parseInt(ret[1]));}
if(!this.url){return;}
var domain=this.url.replace(/^.*\/\//,'').replace(/\/.*/,''),timer=this.eTime-this.sTime,cgi=encodeURIComponent(this.formatUrl?this.url.match(/^[\w|/|.|:|-]*/)[0]:this.url);this.reportUrl="http://c.isdspeed.qq.com/code.cgi?domain="+domain+"&cgi="+cgi+"&type="+this.retCode+"&code="+this.errCode+"&time="+timer+"&rate="+this.frequence+(this.uin?("&uin="+this.uin):"");if(this.reportUrl&&Math.random()<(1/this.frequence)&&this.url){$report(this.reportUrl);}}
return option;};function $setClass(ids,cName,kind){if(!ids){return;}
var set=function(obj,cName,kind){if(!obj){return;}
var oldName=obj.className,arrName=oldName?oldName.split(' '):[];if(kind=="add"){if(!$hasClass(oldName,cName)){arrName.push(cName);obj.className=arrName.join(' ');}}
else if(kind=="remove"){var newName=[];for(var i=0,l=arrName.length;i<l;i++){if(cName!=arrName[i]&&' '!=arrName[i]){newName.push(arrName[i]);}}
obj.className=newName.join(' ');}};if(typeof(ids)=="string"){var arrDom=ids.split(",");for(var i=0,l=arrDom.length;i<l;i++){if(arrDom[i]){set($id(arrDom[i]),cName,kind);}}}
else if(ids instanceof Array){for(var i=0,l=ids.length;i<l;i++){if(ids[i]){set(ids[i],cName,kind);}}}
else{set(ids,cName,kind);}};function $setCookie(name,value,expires,path,domain,secure){var exp=new Date(),expires=arguments[2]||null,path=arguments[3]||"/",domain=arguments[4]||null,secure=arguments[5]||false;expires?exp.setMinutes(exp.getMinutes()+parseInt(expires)):"";document.cookie=name+'='+escape(value)+(expires?';expires='+exp.toGMTString():'')+(path?';path='+path:'')+(domain?';domain='+domain:'')+(secure?';secure':'');};function $slider(obj){var opt={titleId:"",titleTag:"",contentId:"",contentTag:"",prevId:"",nextId:"",perView:1,className:"current",eventType:"mouseover",initIndex:NaN,timeLag:300,funcInit:$empty(),funcTabInit:$empty(),func:$empty(),onPage:$empty(),nodeWalker:null,auto:false,autoKeep:true,autoTimes:100,autoLag:5000,fadeLag:50,fadeTimes:500,initSpeed:100,effect:'none',width:0,height:0,backAttr:"back_src",isLoadInit:true,focusIndex:setEffect,clearAuto:function(){clearInterval(autoIntr)},cont:null,tabs:null,funcTabChange:$empty()};for(var i in obj){opt[i]=obj[i]};((opt.width==0&&opt.effect=="scrollx")||(opt.height==0&&opt.effect=="scrolly"))&&(opt.effect="none");var total=0,autoCount=0,isInit=true,intr=null,autoIntr=null,_imgs=[];if(opt.contentId){var oContent=$id(opt.contentId),_cont=(opt.nodeWalker||$child)(oContent,opt.contentTag,function(dom){switch(opt.effect){case"none":dom.style.display="none";break;case"scrollx":dom.style.width=opt.width+"px";dom.style.styleFloat=dom.style.cssFloat="left";dom.style.visibility="hidden";break;case"scrolly":dom.style.height=opt.height+"px";dom.style.visibility="hidden";break;case"fade":dom.style.display="none";dom.style.position="absolute";dom.style.left=0;dom.style.top=0;break;};opt.funcInit(total++,dom);});if(opt.auto){$addEvent(oContent,"mouseover",function(){clearInterval(autoIntr);});opt.autoKeep&&$addEvent(oContent,"mouseout",function(){setAuto();});};opt.cont=_cont;}
var len=opt.perView,now=0;if(opt.titleId){var oTitle=$id(opt.titleId),_tabs=(opt.nodeWalker||$child)(oTitle,opt.titleTag,function(dom){opt.funcTabInit(now,dom);dom.setAttribute("index",now++);});$addEvent(oTitle,opt.eventType,function(e){var tar=$getTarget(e,oTitle,opt.titleTag);if(tar&&$inArray(tar,_tabs)!=-1){var cur=tar.getAttribute("index")*1;clearInterval(autoIntr);if(cur!=current){intr=setTimeout(function(){opt.funcTabChange(cur,opt);setEffect(cur);},opt.timeLag);}}});$addEvent(oTitle,"mouseout",function(e){var tar=$getTarget(e,oTitle,opt.titleTag);if(tar){clearTimeout(intr);opt.auto&&opt.autoKeep&&setAuto();}});opt.tabs=_tabs;total=now;};var pageTotal=Math.ceil(total/len),current=isNaN(opt.initIndex)?$randomInt(pageTotal):opt.initIndex,autoTotal=opt.autoTimes*total-1;setEffect(current);opt.auto&&setAuto();if(opt.prevId){if(opt.prevId.indexOf(",")>-1){var prevs=opt.prevId.split(",");for(var i=0,j=prevs.length;i<j;i++){$addEvent($id(prevs[i]),"click",showPrev);}}else{$addEvent($id(opt.prevId),"click",showPrev);}}
if(opt.nextId){if(opt.nextId.indexOf(",")>-1){var nexts=opt.nextId.split(",");for(var i=0,j=nexts.length;i<j;i++){$addEvent($id(nexts[i]),"click",showNext);}}else{$addEvent($id(opt.nextId),"click",showNext);}}
isInit=false;return opt;function setAuto(){autoIntr&&clearInterval(autoIntr);autoIntr=setInterval(function(){if(autoCount>=autoTotal){clearInterval(autoIntr);}else{setEffect((now=current+1)>=pageTotal?0:now);autoCount++;}},opt.autoLag);}
function setEffect(cur){if(cur>=_cont.length)return;if(!opt.contentId){showItem(cur);current=cur;return;};if(isInit){switch(opt.effect){case"scrollx":oContent.style.position="relative";oContent.style.width=(total+1)*opt.width+"px";oContent.style.left=-current*opt.width+"px";break;case"scrolly":oContent.style.position="relative";oContent.style.top=-current*opt.height+"px";break;case"fade":oContent.style.position="relative";break;};for(var i=0;i<len;i++){(now=cur+i)<total&&showItem(now);};opt.onPage(cur);current=cur;}else{var fadeStep=Math.floor(opt.fadeTimes/opt.fadeLag),fadeIntr=null,fadeCount=0;if(opt.globeFadeIntr){switch(opt.effect){case"fade":_cont[current].style.zIndex=0;_cont[cur].style.zIndex=1;_cont[current].style.filter="alpha(opacity=0)";_cont[current].style.opacity=0;_cont[cur].style.filter="alpha(opacity=1)";_cont[cur].style.opacity=1;current=cur;break;}
clearInterval(opt.globeFadeIntr);}
opt.globeFadeIntr=null;switch(opt.effect){case"none":for(var i=0;i<len;i++){(now=current*len+i)<total&&(_cont[now].style.display="none");(now=cur*len+i)<total&&showItem(now);};opt.onPage(cur);current=cur;break;case"scrollx":var left=getSpeed(opt.width);showItem(cur);opt.globeFadeIntr=fadeIntr=setInterval(function(){if(fadeCount++>=fadeStep){clearInterval(fadeIntr);opt.globeFadeIntr=null;oContent.style.left=-left.end+"px";current=cur;}else{oContent.style.left=-getMove(left)+"px";left.t=left.t<opt.fadeTimes?(left.t+opt.fadeLag):opt.fadeTimes;};},opt.fadeLag);break;case"scrolly":var top=getSpeed(opt.height);showItem(cur);opt.globeFadeIntr=fadeIntr=setInterval(function(){if(fadeCount++>=fadeStep){clearInterval(fadeIntr);opt.globeFadeIntr=null;oContent.style.top=-top.end+"px";current=cur;}else{oContent.style.top=-getMove(top)+"px";top.t=top.t<opt.fadeTimes?(top.t+opt.fadeLag):opt.fadeTimes;};},opt.fadeLag);break;case"fade":showItem(cur);opt.globeFadeIntr=fadeIntr=setInterval(function(){if(fadeCount++>=fadeStep){clearInterval(fadeIntr);opt.globeFadeIntr=null;_cont[current].style.zIndex=0;_cont[cur].style.zIndex=1;current=cur;}else{var per=fadeCount/fadeStep;_cont[current].style.filter="alpha(opacity="+(1-per)*100+")";_cont[current].style.opacity=1-per;_cont[cur].style.filter="alpha(opacity="+(per*100)+")";_cont[cur].style.opacity=per;};},opt.fadeLag);break;};}
function getSpeed(s){var flag=(cur-current)<0?-1:1,end=cur*s,here=(cur-flag)*s,oFirst=_cont[0];current==0&&(oFirst.style.position="static");if(current+1==total&&cur==0){flag=1;end=(current+1)*s;here=current*s;oFirst.style.position="relative";opt.effect=="scrollx"?oFirst.style.left=end+"px":oFirst.style.top=end+"px";};return{t:0,distance:flag*s,end:end,here:here}}
function getMove(obj){var b=obj.here,c=obj.distance,d=opt.fadeTimes,t=obj.t/d-1;return parseInt(-c*(t*t*t*t-1)+b,10);}
function showItem(cur){if(cur>=_cont.length)return;if(opt.contentId&&!_imgs[cur]&&(isInit==false||(isInit==true&&opt.isLoadInit==true))){$loadImg(_cont[cur],opt.backAttr);_imgs[cur]=true;};if(opt.contentId){_cont[cur].style.display=="none"&&(_cont[cur].style.display="block");_cont[cur].style.visibility=="hidden"&&(_cont[cur].style.visibility="visible");};if(opt.titleId){for(var i=0,len=_tabs.length;i<len;i++){i!=cur&&$delClass(_tabs[i],opt.className);}
$addClass(_tabs[cur],opt.className);_tabs[cur].style.display=="none"&&(_tabs[cur].style.display="block");};opt.func(cur);}}
function showPrev(e){$preventDefault(e);clearInterval(autoIntr);setEffect((now=current-1)<0?(pageTotal-1):now);}
function showNext(e){$preventDefault(e);clearInterval(autoIntr);setEffect((now=current+1)>=pageTotal?0:now);}};function $time33(str){for(var i=0,len=str.length,hash=5381;i<len;++i){hash+=(hash<<5)+str.charAt(i).charCodeAt();};return hash&0x7fffffff;};$namespace("PP.shop.baoyou");PP.shop.baoyou={};PP.shop.baoyou.init=function(){this.show();this.loadBaoyou();};PP.shop.baoyou.show=function(){var title=$id('tabTitle'),area;if($getQuery("isalone")=='1'){area=$id('interestArea');if(area)$addClass(area,'interest_alone');if(title)title.style.display='';}else{if(title)title.style.display='none';}}
PP.shop.baoyou.loadBaoyou=function(){var martIds=['101338','101337','101339','101340','101341','101342','101343','101344','101346','101348'];$slider({titleId:"baoyouTitle",titleTag:"li",contentId:"baoyouContent",contentTag:"ul",className:"current",func:function(i){var item=this.cont[i],load;if(item){load=item.getAttribute('data-loaded');if(load!='1'){showBaoyou(i,item);}}}});function showBaoyou(index,dom){var url='http://r.paipai.com/tws/cpcad/cpc_search?adsbannerid='+(martIds[index]||'')+'&pagesize=6&curl='+encodeURIComponent(location.href.split('?')[0])+'&pps=&t='+Math.random();PP.shop.baoyou.loadObj.loadData(url,function(obj,reCoder){try{var datas=obj.data.adList,model=$id('baoyouTpl');if(!dom||!model){reCoder.report(false,CPCADERR.LACKDOM);return false;}
if(datas.length==0){reCoder.report(true,CPCADERR.EMPTY);return false;}
dom.innerHTML=$formatJson(model.innerHTML,{data:datas})
dom.setAttribute('data-loaded','1');reCoder.report(true,CPCADERR.FINISH);}catch(e){reCoder.report(false,CPCADERR.EXECERR);}},'bizId=baoyou');}};PP.shop.baoyou.loadObj={_guid:1000,loadData:function(url,cb,returnId){var cbName='cpcadCallback'+this._guid++,reCoder=$returnCode({url:returnId?(url.split('?')[0]+'?'+returnId):url,formatUrl:returnId?false:true}),timeoutTag;$loadScript(url+'&callback='+cbName);window[cbName]=function(obj){clearTimeout(timeoutTag);if(obj.errCode==0){cb&&cb(obj,reCoder);}else{reCoder.report(false,CPCADERR.SYSERR);}}
timeoutTag=setTimeout(function(){reCoder.report(false,CPCADERR.TIMEOUT);window[cbName]=$empty();},15000);}}
var CPCADERR={TIMEOUT:11,SYSERR:12,EMPTY:13,NOTENOUGH:14,LACKDOM:15,EXECERR:16,FINISH:20}
PP.shop.baoyou.init();
window['PP.shop.baoyou']='21638:20150325:20150325111324';
window['PP.shop.baoyou.time'] && window['PP.shop.baoyou.time'].push(new Date());/*  |xGv00|21b0ce615522e93ada5ecf266be68355 */