window['PP.wg.buy.time'] && window['PP.wg.buy.time'].push(new Date());
function $addClass(ids,cName){$setClass(ids,cName,"add");};function $addToken(url,type,skey){var token=$getToken(skey);if(url==""||(url.indexOf("://")<0?location.href:url).indexOf("http")!=0){return url;}
if(url.indexOf("#")!=-1){var f1=url.match(/\?.+\#/);if(f1){var t=f1[0].split("#"),newPara=[t[0],"&g_tk=",token,"&g_ty=",type,"#",t[1]].join("");return url.replace(f1[0],newPara);}else{var t=url.split("#");return[t[0],"?g_tk=",token,"&g_ty=",type,"#",t[1]].join("");}}
return token==""?(url+(url.indexOf("?")!=-1?"&":"?")+"g_ty="+type):(url+(url.indexOf("?")!=-1?"&":"?")+"g_tk="+token+"&g_ty="+type);};(function(){var queue=[],timer=null,IE=$isBrowser("ie");var rfxnum=/^([+\-]=)?([\d+.\-]+)([a-z%]*)$/i,ropacity=/opacity=([^)]*)/i,opacityReg=/opacity/i,colorReg=/color/i,padMar=/^(padding|margin)$/i,borderReg=/^border$/i
cssNumber={"fillOpacity":true,"fontWeight":true,"lineHeight":true,"opacity":true,"orphans":true,"widows":true,"zIndex":true,"zoom":true};var eases={liner:function(t,b,c,d){return c*t/d+b;},easeIn:function(t,b,c,d){return c*(t/=d)*t+b;},easeOut:function(t,b,c,d){return-c*(t/=d)*(t-2)+b;},easeBoth:function(t,b,c,d){if((t/=d/2)<1){return c/2*t*t+b;}return-c/2*((--t)*(t-2)-1)+b;},easeInStrong:function(t,b,c,d){return c*(t/=d)*t*t*t+b;},easeOutStrong:function(t,b,c,d){return-c*((t=t/d-1)*t*t*t-1)+b;},easeBothStrong:function(t,b,c,d){if((t/=d/2)<1){return c/2*t*t*t*t+b;}return-c/2*((t-=2)*t*t*t-2)+b;},elasticIn:function(t,b,c,d,a,p){var s;if(t===0){return b;}if((t/=d)===1){return b+c;}if(!p){p=d*0.3;}if(!a||a<Math.abs(c)){a=c;s=p/4;}else{s=p/(2*Math.PI)*Math.asin(c/a);}return-(a*Math.pow(2,10*(t-=1))*Math.sin((t*d-s)*(2*Math.PI)/p))+b;},elasticOut:function(t,b,c,d,a,p){var s;if(t===0){return b;}if((t/=d)===1){return b+c;}if(!p){p=d*0.3;}if(!a||a<Math.abs(c)){a=c;s=p/4;}else{s=p/(2*Math.PI)*Math.asin(c/a);}return a*Math.pow(2,-10*t)*Math.sin((t*d-s)*(2*Math.PI)/p)+c+b;},elasticBoth:function(t,b,c,d,a,p){var s;if(t===0){return b;}if((t/=d/2)===2){return b+c;}if(!p){p=d*(0.3*1.5);}if(!a||a<Math.abs(c)){a=c;s=p/4;}else{s=p/(2*Math.PI)*Math.asin(c/a);}if(t<1){return-0.5*(a*Math.pow(2,10*(t-=1))*Math.sin((t*d-s)*(2*Math.PI)/p))+b;}return a*Math.pow(2,-10*(t-=1))*Math.sin((t*d-s)*(2*Math.PI)/p)*0.5+c+b;},backIn:function(t,b,c,d,s){if(s===undefined){s=1.70158;}if(t===d){t-=0.001;}return c*(t/=d)*t*((s+1)*t-s)+b;},backOut:function(t,b,c,d,s){if(typeof s==='undefined'){s=1.70158;}return c*((t=t/d-1)*t*((s+1)*t+s)+1)+b;},backBoth:function(t,b,c,d,s){if(typeof s==='undefined'){s=1.70158;}if((t/=d/2)<1){return c/2*(t*t*(((s*=(1.525))+1)*t-s))+b;}return c/2*((t-=2)*t*(((s*=(1.525))+1)*t+s)+2)+b;},bounceIn:function(t,b,c,d){return c-eases.bounceOut(d-t,0,c,d)+b;},bounceOut:function(t,b,c,d){if((t/=d)<(1/2.75)){return c*(7.5625*t*t)+b;}else if(t<(2/2.75)){return c*(7.5625*(t-=(1.5/2.75))*t+0.75)+b;}else if(t<(2.5/2.75)){return c*(7.5625*(t-=(2.25/2.75))*t+0.9375)+b;}return c*(7.5625*(t-=(2.625/2.75))*t+0.984375)+b;},bounceBoth:function(t,b,c,d){if(t<d/2){return eases.bounceIn(t*2,0,c,d)*0.5+b;}return eases.bounceOut(t*2-d,0,c,d)*0.5+c*0.5+b;}}
function camelCase(str){return str.replace(/^-ms-/,"ms-").replace(/-([a-z]|[0-9])/ig,function(all,letter){return(letter+"").toUpperCase();})}
var Fx=function(ele,prop,option){this.opt={speed:1000,ease:"liner",onInit:null,onStart:null,onComplete:null,initStart:true};this.ele=$id(ele);this.prop=prop;this.option=option;for(var o in option){this.opt[o]=option[o];}
this.ease=('function'==typeof this.opt.ease)?this.opt.ease:eases[this.opt.ease]||eases["liner"];}
var Anim=function(){this.init.apply(this,arguments);};Anim.prototype.init=function(ele,prop,option){this.fxs=[];this.pFxs=[];this.rFxs=[];this.curPart=0;if(prop){this.fxs.push(new Fx(ele,prop,option));}
this.isEnd=false;return this.runFx();};Anim.prototype.runFx=function(fxp){var fx=fxp,pushInPfx=true;if(!fx){fx=this.fxs.shift();var nextFx=this.fxs[0];if(fx==="prev"){if(this.pFxs.length==0)return false;this.curPart--;fx=this.pFxs.pop();this.rFxs.push(fx);this.prop=fx._prop;pushInPfx=false;}else if(fx==="next"){if(this.rFxs.length==0)return false;this.curPart++;fx=this.rFxs.pop();this.pFxs.push(fx);this.prop=fx.prop;pushInPfx=false;}}
if(pushInPfx){while(this.rFxs.length>0){this.pFxs.push(this.rFxs.pop());}
this.curPart++;this.pFxs.push(fx);this.prop=fx.prop;}
this.fx=fx;this.opt=fx.opt;this.ease=fx.ease;this.ele=fx.ele;this.curframe=1;this.frames=Math.ceil((this.opt.speed/1000)*35);this.initProp();this.opt.onInit&&this.opt.onInit.call(this);if(this.opt.initStart){this.overflow&&(this.ele.style.overflow="hidden");this.start();return true;}else return false;}
Anim.prototype.initProp=function(){this.camelProp();this.oriAtt={};this.units={};var val,parts,csparts,num,elem=this.ele;for(var name in this.prop){var cs=elem.style[name]?$curStyle(elem,name):elem[name];if(name.match(colorReg)){if(name=="borderColor"){cs=$curStyle(elem,"borderLeftColor");}
this.oriAtt[name]=convertColor(cs);this.prop[name]=convertColor(this.prop[name]);}else{csparts=rfxnum.exec(cs);if(csparts&&csparts[2]){cs=parseFloat(csparts[2]);}
if(name.match(opacityReg)){if(IE){cs=ropacity.test((elem.currentStyle?elem.currentStyle.filter:elem.style.filter)||"")?(parseFloat(RegExp.$1)/100):1;}else{cs!=0&&!cs&&(cs=1);}}
cs=cs!=0&&!cs?0:cs==="auto"?0:cs;this.oriAtt[name]=cs;val=this.prop[name];parts=rfxnum.exec(val);if(parts){num=parseFloat(parts[2]);this.units[name]=parts[3]||(cssNumber[name]?"":"px");if(parts[1]){num=(parts[1]==="-="?-num:num)+cs;}
this.prop[name]=num;}}}
this.fx._prop=$extend(this.oriAtt);};Anim.prototype.camelProp=function(){var elem=this.ele;for(var p in this.prop){name=camelCase(p);if(name.match(padMar)){var that=this;$each(["Top","Right","Bottom","Left"],function(fn){that.prop[name+fn]=that.prop[p];});delete this.prop[p];continue;}if(name.match(borderReg)){this.prop[name+"Width"]=this.prop[p];delete this.prop[p];continue;}
if(p!==name){this.prop[name]=this.prop[p];delete this.prop[p];}
if(name==="height"||name==="width"){var dplay=$curStyle(elem,"display"),flo=$curStyle(elem,"float");if(dplay==="inline"&&(!flo||flo==="none")){elem.style.display="inline-block";}
if(!this.overflow){this.overflow=[elem.style.overflow,elem.style.overflowX,elem.style.overflowY];}}}};Anim.prototype.start=function(){!this.opt.initStart&&(this.opt.initStart=true);if(this.isEnd)return;this.isStop=false;var exist=false;for(var i=0;i<queue.length;++i){if(queue[i]===this){exist=true;break;}}!exist&&queue.push(this);this.opt.onStart&&this.opt.onStart.call(this);if(!timer){timer=window.setTimeout(execAnims,13);}};Anim.prototype.stop=function(end){this.isStop=true;this.isEnd=!!end;};Anim.prototype.step=function(){if(this.curframe>this.frames){if(this.fxs.length>0){this.opt.onComplete&&this.opt.onComplete.call(this);return this.runFx();}else{this.isEnd=true;var overflows=this.overflow;if(overflows){var elem=this.ele;$each(["","X","Y"],function(jn,i){elem.style["overflow"+jn]=overflows[i];});}
this.opt.onComplete&&this.opt.onComplete.call(this);return false;}}
var prop=this.prop,fn;for(var p in prop){fn=this.attFns[p]||this.attFns["defFn"];fn.call(this,p);}
this.curframe++;return true;};Anim.prototype.next=function(prop,option){if(prop){this.fxs.push(new Fx(this.ele,prop,option));}else{this.fxs.push("next");}
return this;};Anim.prototype.nextAll=function(){var temp=[],len=this.fxs.length;for(var i=0;i<len;++i){var fx=this.fxs[i];if(fx==="prev"){temp.push("next");}};this.fxs=this.fxs.concat(temp);return this;};Anim.prototype.prev=function(){this.fxs.push("prev");return this;};Anim.prototype.prevAll=function(){var temp=["prev"],len=this.fxs.length;for(var i=0;i<len;++i){var fx=this.fxs[i];if(fx instanceof Fx||fx==="next"){temp.push("prev");}else if(fx==="prev"){temp.pop();}};this.fxs=this.fxs.concat(temp);return this;};Anim.prototype.execEase=function(from,to){var args=[this.curframe,from,to-from,this.frames];return this.ease.apply(this,args);};Anim.prototype.attFns={opacity:function(p){var style=this.ele.style,res=this.isEnd?this.prop[p]:this.execEase(this.oriAtt[p],this.prop[p]);if(IE){style['filter']='alpha(opacity='+Math.round(res*100)+')';}else{style[p]=res;}},defFn:function(p){var res=this.isEnd?this.prop[p]:this.execEase(this.oriAtt[p],this.prop[p]);this.ele.style[p]?(this.ele.style[p]=res+this.units[p]):(this.ele[p]=res);}}
$each(["width","height","paddingLeft","paddingRight","paddingTop","paddingBottom"],function(jn){Anim.prototype.attFns[jn]=function(p){var res=this.isEnd?this.prop[p]:this.execEase(this.oriAtt[p],this.prop[p]);this.ele.style[p]=Math.max(0,res)+this.units[p];};});$each(["color","backgroundColor","borderColor","borderLeftColor","borderRightColor","borderTopColor","borderBottomColor"],function(jn){Anim.prototype.attFns[jn]=function(p){var res="",ori=this.oriAtt[p],pro=this.prop[p];if(this.isEnd){res="rgb("+pro.join(",")+")";}else{var r=Math.round(this.execEase(ori[0],pro[0]));var g=Math.round(this.execEase(ori[1],pro[1]));var b=Math.round(this.execEase(ori[2],pro[2]));res="rgb("+r+","+g+","+b+")";}
this.ele.style[p]=res;};});function convertColor(color){var cS=color.split('#');if(cS[1]){cS=cS[1].split('');cS=cS.length<6?(cS[0]+cS[0]+cS[1]+cS[1]+cS[2]+cS[2]).split(''):cS;return[parseInt(cS[0]+cS[1],16),parseInt(cS[2]+cS[3],16),parseInt(cS[4]+cS[5],16)];}else{var rgbs=/rgb\((.*)\)/.exec(cS[0])[1].replace(/\s*/g,'').split(',');return[parseInt(rgbs[0],10),parseInt(rgbs[1],10),parseInt(rgbs[2],10)]}};function execAnims(){for(var i=0;i<queue.length;++i){var anim=queue[i];if((anim.isStop||!anim.step())&&queue[i]===anim){queue.splice(i--,1);}}
if(queue.length>0){timer=window.setTimeout(arguments.callee,13);}else{timer=null;}}
window.$animation=function(ele,prop,option){return new Anim(ele,prop,option);}})();function $autoLoadImages(option){var opt={scrollOffsetH:100,initSrcName:'init_src'};if(option){for(var key in option){opt[key]=option[key];}}
if(window['_PP_core_autoLoadImages_data']){if(window['_PP_core_autoLoadImages_data'].nosrcLength==0){clearInterval(window._PP_core_autoLoadImages_data.ptr);window._PP_core_autoLoadImages_data.ptr=setInterval(function(){doScroll();},100);}
window['_PP_core_autoLoadImages_data'].allNum=0;return;}
window['_PP_core_autoLoadImages_data']={allNum:0,nosrcImages:[],nosrcLength:0,ciguid:0,ptr:null};clearInterval(window._PP_core_autoLoadImages_data.ptr);window._PP_core_autoLoadImages_data.ptr=setInterval(function(){doScroll()},100);function doScroll(){var data=window['_PP_core_autoLoadImages_data'],allImage=document.images;if(allImage.length>data.allNum){data.nosrcImages=[];for(var i=0,j=allImage.length;i<j;i++){var src=allImage[i].getAttribute(opt.initSrcName);if(src&&!allImage[i].getAttribute("iguid")){data.nosrcImages.push([allImage[i],src,$getY(allImage[i])]);}}
data.nosrcLength=data.nosrcImages.length;data.allNum=allImage.length;}
if(data.nosrcLength==0){if(data.ptr!=null){clearInterval(data.ptr);data.ptr=null;data.allNum=0;data.nosrcImages=[];}
return;};var bodyCache=document.body,domCache=(document.compatMode=='BackCompat')?bodyCache:document.documentElement,offsetH=window.pageYOffset||document.documentElement.scrollTop||document.body.scrollTop,visibleH=offsetH+domCache.clientHeight;for(var i=0,j=data.nosrcImages.length;i<j;i++){if(!data.nosrcImages[i]){continue;}
if((visibleH+opt.scrollOffsetH)>data.nosrcImages[i][2]){var _item=data.nosrcImages[i];_item[0].setAttribute("src",_item[1]);_item[0].setAttribute("iguid",data.ciguid++);delete data.nosrcImages[i];data.nosrcLength--;}}}};$break=window["$break"]||function(t){return t===window["$break"];};function $curStyle(obj,prop){if(obj.currentStyle){return obj.currentStyle[prop];}
else if(window.getComputedStyle){prop=prop.replace(/([A-Z])/g,"-$1");prop=prop.toLowerCase();return window.getComputedStyle(obj,null).getPropertyValue(prop);}
return null;};function $delClass(ids,cName){$setClass(ids,cName,"remove");};function $each(jn,fn){var len=jn.length;if("number"===typeof len){for(var i=0;i<len;i++){try{fn(jn[i],i);}catch(e){if($break(e)){break;}else{throw e;};}}}else{for(var k in jn){try{fn(jn[k],k);}catch(e){if($break(e)){break;}else{throw e;};}}}};function $empty(){return function(){return true;}};function $extend(){var target=arguments[0]||{},i=1,length=arguments.length,options;if(typeof target!="object"&&typeof target!="function")
target={};for(;i<length;i++)
if((options=arguments[i])!=null)
for(var name in options){var copy=options[name];if(target===copy)
continue;if(copy!==undefined)
target[name]=copy;}
return target;};function $fireEvent(dom,type,eType){var dom=$id(dom),type=type||"click",eType=eType||"MouseEvents";if(dom==document&&document.createEvent&&!dom.dispatchEvent){dom=document.documentElement;}
var e;if(document.createEvent){e=document.createEvent(eType);e.initEvent(type,true,true);dom.dispatchEvent(e);}else{e=document.createEventObject();e.eventType="on"+type;dom.fireEvent(e.eventType,event);}};(function(){var _formatJson_cache={};$formatJson=function(str,data){var fn=!/\W/.test(str)?_formatJson_cache[str]=_formatJson_cache[str]||$formatJson($id(str).innerHTML):new Function("obj","var p=[],print=function(){p.push.apply(p,arguments);};"+"with(obj){p.push('"+str.replace(/[\r\t\n]/g," ").split("<%").join("\t").replace(/((^|%>)[^\t]*)'/g,"$1\r").replace(/\t=(.*?)%>/g,"',$1,'").split("\t").join("');").split("%>").join("p.push('").split("\r").join("\\'")+"');}return p.join('');");return data?fn(data):fn;}})();function $getCookie(name){var reg=new RegExp("(^| )"+name+"(?:=([^;]*))?(;|$)"),val=document.cookie.match(reg);return val?(val[2]?unescape(val[2]):""):null;};function $getImageUrlBySize(imgurl,size){if($strTrim(imgurl)=='')return'';if(imgurl.indexOf('qqbuy')>-1){return imgurl.replace(/\/\d+\?/g,'/'+size+'?');}else{var arr=imgurl.split(/\.\d\./);if(arr[1]){arr[1]=arr[1].replace(/\d+x\d+\./,'');return arr[0]+(/\.\d\./).exec(imgurl)[0]+size+'x'+size+'.'+arr[1];}else{return imgurl;}}};function $getQuery(name,url){var u=arguments[1]||window.location.search,reg=new RegExp("(^|&)"+name+"=([^&]*)(&|$)"),r=u.substr(u.indexOf("\?")+1).match(reg);return r!=null?r[2]:"";};function $getToken(skey){var skey=skey?skey:$getCookie("skey");return skey?$time33(skey):"";};function $getUin(){var uin=$getCookie("uin")||$getCookie('uin_cookie')||$getCookie('pt2gguin')||$getCookie('o_cookie')||$getCookie('luin')||$getCookie('buy_uin');return uin?parseInt(uin.replace("o",""),10):"";};function $getY(e){var t=e.offsetTop||0;while(e=e.offsetParent){t+=e.offsetTop;}
return t;};function $hasClass(old,cur){if(!old||!cur)return null;var arr=(typeof old=='object'?old.className:old).split(' ');for(var i=0,len=arr.length;i<len;i++){if(cur==arr[i]){return cur;}};return null;};function $id(id){return typeof(id)=="string"?document.getElementById(id):id;};function $isBrowser(str){str=str.toLowerCase();var b=navigator.userAgent.toLowerCase();var arrB=[];arrB['firefox']=b.indexOf("firefox")!=-1;arrB['opera']=b.indexOf("opera")!=-1;arrB['safari']=b.indexOf("safari")!=-1;arrB['chrome']=b.indexOf("chrome")!=-1;arrB['gecko']=!arrB['opera']&&!arrB['safari']&&b.indexOf("gecko")>-1;arrB['ie']=!arrB['opera']&&b.indexOf("msie")!=-1;arrB['ie6']=!arrB['opera']&&b.indexOf("msie 6")!=-1;arrB['ie7']=!arrB['opera']&&b.indexOf("msie 7")!=-1;arrB['ie8']=!arrB['opera']&&b.indexOf("msie 8")!=-1;arrB['ie9']=!arrB['opera']&&b.indexOf("msie 9")!=-1;arrB['ie10']=!arrB['opera']&&b.indexOf("msie 10")!=-1;return arrB[str];};function $isLogin(){return($getCookie("p_skey")&&$getCookie("p_uin")||$getCookie("skey")&&$getCookie("uin"))?true:false;};function $loadScript(obj){if(!$loadScript.counter){$loadScript.counter=1;}
var isObj=typeof(obj)=="object",url=isObj?obj.url:arguments[0],id=isObj?obj.id:arguments[1],obj=isObj?obj:arguments[2],_head=document.head||document.getElementsByTagName("head")[0]||document.documentElement,_script=document.createElement("script"),D=new Date(),_time=D.getTime(),_isCleared=false,_timer=null,o=obj||{},data=o.data||'',charset=o.charset||"gb2312",isToken=o.isToken,skey=o.skey,timeout=o.timeout,isAutoReport=o.isAutoReport||false,reportOptions=o.reportOptions||{},reportType=o.reportType||'current',reportRetCodeName=o.reportRetCodeName,reportSuccessCode=typeof(o.reportSuccessCode)=="undefined"?200:o.reportSuccessCode,reportErrorCode=typeof(o.reportErrorCode)=="undefined"?500:o.reportErrorCode,reportTimeoutCode=typeof(o.reportTimeoutCode)=="undefined"?600:o.reportTimeoutCode,onload=o.onload,onsucc=o.onsucc,callbackName=o.callbackName||'',callback=o.callback,errorback=o.errorback,_jsonpLoadState='uninitialized';var complete=function(errCode){if(!_script||_isCleared){return;}
_isCleared=true;if(_timer){clearTimeout(_timer);_timer=null;}
_script.onload=_script.onreadystatechange=_script.onerror=null;if(_head&&_script.parentNode){_head.removeChild(_script);}
_script=null;if(callbackName){if(callbackName.indexOf('.')==-1){window[callbackName]=null;try{delete window[callbackName];}
catch(e){}}
else{var arrJ=callbackName.split("."),p={};for(var j=0,jLen=arrJ.length;j<jLen;j++){var n=arrJ[j];if(j==0){p=window[n];}
else{if(j==jLen-1){try{delete p[n];}
catch(e){}}
else{p=p[n];}}}}}
if(_jsonpLoadState!="loaded"&&typeof errorback=="function"){errorback(errCode);}
if(isAutoReport&&reportType!='cross'){_retCoder.report(_jsonpLoadState=="loaded",errCode);}};var jsontostr=function(d){var a=[];for(var k in d){a.push(k+'='+d[k]);}
return a.join('&');};if(isAutoReport&&reportOptions){if(reportType=='cross'){$returnCode(reportOptions).reg();}
else{reportOptions.url=reportOptions.url||url.substr(0,url.indexOf('?')==-1?url.length:url.indexOf('?'));var _retCoder=$returnCode(reportOptions);}}
if(data){url+=(url.indexOf("?")!=-1?"&":"?")+(typeof data=='string'?data:jsontostr(data));}
if(callbackName&&typeof callback=="function"){var oldName=callbackName;if(callbackName.indexOf('.')==-1){callbackName=window[callbackName]?callbackName+$loadScript.counter++:callbackName;window[callbackName]=function(jsonData){_jsonpLoadState='loaded';if(isAutoReport&&reportRetCodeName){reportSuccessCode=jsonData[reportRetCodeName];}
callback.apply(null,arguments);onsucc&&(onsucc());};}
else{var arrJ=callbackName.split("."),p={},arrF=[];for(var j=0,jLen=arrJ.length;j<jLen;j++){var n=arrJ[j];if(j==0){p=window[n];}
else{if(j==jLen-1){p[n]?(n=n+$loadScript.counter++):'';p[n]=function(jsonData){_jsonpLoadState='loaded';if(isAutoReport&&reportRetCodeName){reportSuccessCode=jsonData[reportRetCodeName];}
callback.apply(null,arguments);onsucc&&(onsucc());};}
else{p=p[n];}}
arrF.push(n);}
callbackName=arrF.join('.');}
url=url.replace('='+oldName,'='+callbackName);}
_jsonpLoadState='loading';id=id?(id+_time):_time;url=(isToken!==false?$addToken(url,"ls",skey):url);_script.charset=charset;_script.id=id;_script.onload=_script.onreadystatechange=function(){var uA=navigator.userAgent.toLowerCase();if(!(!(uA.indexOf("opera")!=-1)&&uA.indexOf("msie")!=-1)||/loaded|complete/i.test(this.readyState)){if(typeof onload=="function"){onload();}
complete(_jsonpLoadState=="loaded"?reportSuccessCode:reportErrorCode);}};_script.onerror=function(){complete(reportErrorCode);};if(timeout){_timer=setTimeout(function(){complete(reportTimeoutCode);},parseInt(timeout,10));}
setTimeout(function(){_script.src=url;try{_head.insertBefore(_script,_head.lastChild);}catch(e){}},0);};function $loadUrl(o){o.element=o.element||'script';var el=document.createElement(o.element);el.charset=o.charset||'utf-8';o.onBeforeSend&&o.onBeforeSend(el);el.onload=el.onreadystatechange=function(){if(/loaded|complete/i.test(this.readyState)||navigator.userAgent.toLowerCase().indexOf("msie")==-1){o.onLoad&&o.onLoad();clear();}};el.onerror=function(){clear();};el.src=o.url;document.getElementsByTagName('head')[0].appendChild(el);function clear(){if(!el){return;}
el.onload=el.onreadystatechange=el.onerror=null;el.parentNode&&(el.parentNode.removeChild(el));el=null;}};function $makeUrl(data){var arr=[];for(var k in data){arr.push(k+"="+data[k]);};return arr.join("&");};function $mouseover(obj,func){obj.onmouseover=function(e){var e=window.event||e,target=e.fromElement||e.relatedTarget,parent=target;while(parent&&parent!==this){parent=parent.parentNode;}
if(parent!==this){func(this);}}};function $namespace(name){for(var arr=name.split(','),r=0,len=arr.length;r<len;r++){for(var i=0,k,name=arr[r].split('.'),parent={};k=name[i];i++){i===0?eval('(typeof '+k+')==="undefined"?('+k+'={}):"";parent='+k):(parent=parent[k]=parent[k]||{});}}};function $report(url){$loadUrl({'url':url+((url.indexOf('?')==-1)?'?':'&')+Math.random(),'element':'img'});};function $returnCode(opt){var option={url:"",action:"",sTime:"",eTime:"",retCode:"",errCode:"",frequence:1,refer:"",uin:"",domain:"paipai.com",from:1,report:report,isReport:false,timeout:3000,timeoutCode:444,formatUrl:true,reg:reg};try{option['refer']=location.href;}catch(e){}
for(var i in opt){option[i]=opt[i];}
if(option.url){option.sTime=new Date();}
if(option.timeout){setTimeout(function(){if(!option.isReport){option.report(false,option.timeoutCode);}},option.timeout);}
function reg(){this.sTime=new Date();if(!this.action){return;}
var rcookie=$getCookie("retcode"),cookie2=[];rcookie=rcookie?rcookie.split("|"):[];for(var i=0;i<rcookie.length;i++){if(rcookie[i].split(",")[0]!=this.action){cookie2.push(rcookie[i]);}}
cookie2.push(this.action+","+this.sTime.getTime());$setCookie("retcode",cookie2.join("|"),60,"/",this.domain);}
function report(ret,errid){if(this.isReport==true){return;}
this.isReport=true;this.eTime=new Date();this.retCode=ret?1:2;this.errCode=isNaN(parseInt(errid))?"0":parseInt(errid);if(this.action){this.url="http://retcode.paipai.com/"+this.action;var rcookie=$getCookie("retcode"),ret="",ncookie=[];rcookie=rcookie?rcookie.split("|"):[];for(var i=0;i<rcookie.length;i++){if(rcookie[i].split(",")[0]==this.action){ret=rcookie[i].split(",");}
else{ncookie.push(rcookie[i]);}}
$setCookie("retcode",ncookie.join("|"),60,"/",this.domain);if(!ret){return;}
this.sTime=new Date(parseInt(ret[1]));}
if(!this.url){return;}
var domain=this.url.replace(/^.*\/\//,'').replace(/\/.*/,''),timer=this.eTime-this.sTime,cgi=encodeURIComponent(this.formatUrl?this.url.match(/^[\w|/|.|:|-]*/)[0]:this.url);this.reportUrl="http://c.isdspeed.qq.com/code.cgi?domain="+domain+"&cgi="+cgi+"&type="+this.retCode+"&code="+this.errCode+"&time="+timer+"&rate="+this.frequence+(this.uin?("&uin="+this.uin):"");if(this.reportUrl&&Math.random()<(1/this.frequence)&&this.url){$report(this.reportUrl);}}
return option;};function $setClass(ids,cName,kind){if(!ids){return;}
var set=function(obj,cName,kind){if(!obj){return;}
var oldName=obj.className,arrName=oldName?oldName.split(' '):[];if(kind=="add"){if(!$hasClass(oldName,cName)){arrName.push(cName);obj.className=arrName.join(' ');}}
else if(kind=="remove"){var newName=[];for(var i=0,l=arrName.length;i<l;i++){if(cName!=arrName[i]&&' '!=arrName[i]){newName.push(arrName[i]);}}
obj.className=newName.join(' ');}};if(typeof(ids)=="string"){var arrDom=ids.split(",");for(var i=0,l=arrDom.length;i<l;i++){if(arrDom[i]){set($id(arrDom[i]),cName,kind);}}}
else if(ids instanceof Array){for(var i=0,l=ids.length;i<l;i++){if(ids[i]){set(ids[i],cName,kind);}}}
else{set(ids,cName,kind);}};function $setCookie(name,value,expires,path,domain,secure){var exp=new Date(),expires=arguments[2]||null,path=arguments[3]||"/",domain=arguments[4]||null,secure=arguments[5]||false;expires?exp.setMinutes(exp.getMinutes()+parseInt(expires)):"";document.cookie=name+'='+escape(value)+(expires?';expires='+exp.toGMTString():'')+(path?';path='+path:'')+(domain?';domain='+domain:'')+(secure?';secure':'');};function $strTrim(str,code){var argus=code||"\\s";var temp=new RegExp("(^"+argus+"*)|("+argus+"*$)","g");return str.replace(temp,"");};function $time33(str){for(var i=0,len=str.length,hash=5381;i<len;++i){hash+=(hash<<5)+str.charAt(i).charCodeAt();};return hash&0x7fffffff;};function $xss(str,type){if(!str){return str===0?"0":"";}
switch(type){case"none":return str+"";break;case"html":return str.replace(/[&'"<>\/\\\-\x00-\x09\x0b-\x0c\x1f\x80-\xff]/g,function(r){return"&#"+r.charCodeAt(0)+";"}).replace(/ /g,"&nbsp;").replace(/\r\n/g,"<br />").replace(/\n/g,"<br />").replace(/\r/g,"<br />");break;case"htmlEp":return str.replace(/[&'"<>\/\\\-\x00-\x1f\x80-\xff]/g,function(r){return"&#"+r.charCodeAt(0)+";"});break;case"url":return escape(str).replace(/\+/g,"%2B");break;case"miniUrl":return str.replace(/%/g,"%25");break;case"script":return str.replace(/[\\"']/g,function(r){return"\\"+r;}).replace(/%/g,"\\x25").replace(/\n/g,"\\n").replace(/\r/g,"\\r").replace(/\x01/g,"\\x01");break;case"reg":return str.replace(/[\\\^\$\*\+\?\{\}\.\(\)\[\]]/g,function(a){return"\\"+a;});break;default:return escape(str).replace(/[&'"<>\/\\\-\x00-\x09\x0b-\x0c\x1f\x80-\xff]/g,function(r){return"&#"+r.charCodeAt(0)+";"}).replace(/ /g,"&nbsp;").replace(/\r\n/g,"<br />").replace(/\n/g,"<br />").replace(/\r/g,"<br />");break;}};$namespace("PP.wg.buy");PP.wg.buy={size:6,wid:930,contdom:$id("contents"),vptag:"33683.2.",fptag:"33683.3.",sceneId:1009};PP.wg.buy.init=function(){this.tabchange();this.guess();this.viewed();this.favored();this.express();this.setscroll();};PP.wg.buy.tabchange=function(){(function($){tabs($('#tabs li'),$('#contents > div.mod_rec'));function tabs(moveObj,boxObj,changeType){var a=moveObj,ul=boxObj,index=0,timeOut=5e3;a.eq(0).addClass('current');ul.hide().eq(0).show();var current_i=0;a.bind(changeType||'click',function(){index=a.index(this);$(this).addClass('current').siblings(moveObj).removeClass('current');ul.eq(index).show().siblings(boxObj).hide();current_i=index;return false;});setInterval(function(){loopDo();},timeOut);function loopDo(){if(current_i>a.size()-1){current_i=0;}
if(a.eq(current_i).size()==0||a.eq(current_i).is(':hidden')){current_i++;loopDo();return;}
a.removeClass('current').eq(current_i).addClass('current');ul.hide().eq(current_i).show();current_i++;}};})($jq);};PP.wg.buy.guess=function(){var that=this;var o={curPage:0,pageSize:that.size,autoHdisabled:false,url:"http://express.paipai.com/tws/item/favoritemshow_v1?callback=favoritemCb&sceneId={#sid#}&ps={#ps#}",guessdom:$id("guessList")}
var sid2AdpairIds={1014:103182};var adId2PosId={103182:10044177,103183:10044178};o.loadFavoritems=function(uin,itemId,sid,num,ptag,scroll,sw){var url=this.url;if(1014==that.sceneId){var doc=document;try{doc=(window.top&&window.top.document)?window.top.document:doc;}catch(e){}
var curl=doc.location;var ref=doc.referrer||"";var adID=(that.adGuessId||(sid2AdpairIds[this.sceneId]||103183));var posId=(adId2PosId[adID]||0);var ps=that.pageSize||6;try{}catch(e){}
url="http://r.paipai.com/tws/cpcad/cpc_search?callback=favoritemCb&adsbannerid="+adID+"&adpos="+posId+"&curl="+encodeURIComponent(curl)+"&ref="+encodeURIComponent(ref)+"&start=0&pagesize="+ps+"&ptag=&pps=";try{console.log('Load ',url);}catch(e){}
window.favoritemCb=function(json){if(json&&json.errCode==0){var datas=json.data.adList;for(var i=0,il=datas.length;i<il;i++){datas[i].clickUrl=datas[i].commodityUrl||datas[i].clickUrl;datas[i].price=datas[i].newPrice||datas[i].price;datas[i].commodityName=datas[i].commodityName||datas[i].recmdRegName;}
o.guessdom.innerHTML=$xss($formatJson("itemTpl",{arr:datas,ptag:ptag}),"none");$autoLoadImages();if(scroll){that.scroll(datas.length,that.size,sw,$id("guess_prev"),$id("guess_next"),o.guessdom);that.autoscroll($id("guess_next"),Math.ceil(datas.length/that.size));}}else{console.error('错误：',json);}};}else{try{console.error('---Invalid->>>',this.sceneId);}catch(e){}
url=url.replace("{#sid#}",sid).replace("{#ps#}",num);if(uin&&uin!="0"){url+="&qquin="+uin;}
if(itemId){url+="&itemId="+itemId;}
window.favoritemCb=function(json){o.guessdom.innerHTML=$xss($formatJson("itemTpl",{arr:json.data,ptag:ptag}),"none");$autoLoadImages();};}
$loadScript(url);};o.init=function(sid,num,ptag,scroll,sWidth,pageSize){var uin=$getQuery("uin")||$getUin(),itemId=$getQuery("itemId")||"",sid=$getQuery("sid")||sid,ptag=$getQuery("tag")||ptag;this.pageSize=pageSize||4;this.loadFavoritems(uin,itemId,sid,num,ptag,scroll,sWidth);};o.init(that.sceneId,6,"33494.1.1",true,that.wid,that.size);}
PP.wg.buy.viewed=function(){var that=this;$loadScript({id:"viewed",url:"http://my.paipai.com/cgi-bin/vieweditems/get?t="+Math.random(),isToken:true,timeout:3000,isAutoReport:true,reportOptions:{},reportType:"current",callbackName:"viewedGoods",callback:function(data){if(data.errCode!=="0"||data.value==""){var viewedLi=$id("viewedLi");viewedLi.parentNode.removeChild(viewedLi);var viewedDiv=$id("viewedDiv");viewedDiv.parentNode.removeChild(viewedDiv);return;}else{var commlist=data.value.split("{|}").slice(0,that.size);var html=[],tpl='<li><a class="url" href="{#itemUrl#}?PTAG={#ptag#}" target="_blank"><img src="{#imageUrl#}" alt="{#title#}"></a> <p class="price_wrap"><span class="price">&yen;{#price#}</span></p><p class="fn_wrap"><a class="fn" href="{#itemUrl#}?PTAG={#ptag#}" target="_blank">{#title#}</a></p></li>';for(var i=0,len=commlist.length;i<len;i++){var ptag=that.vptag+(i%6+1);var ci=commlist[i];if(/^\s*$/.test(ci)){continue;}
var _item=ci.split("{:}");var key=_item[3].match(/item-\w+-\w{32}\.\d\./);pic=key&&("http://img"+(i+1)+".paipaiimg.com/"+key[0]+"120x120.jpg");html.push(tpl.replace(/{#title#}/g,_item[0]).replace(/{#itemid#}/g,_item[1]).replace(/{#itemUrl#}/g,_item[6]||'http://auction1.paipai.com/'+_item[1]+'?PTAG='+ptag).replace(/{#imageUrl#}/g,pic).replace(/{#price#}/g,_item[4]).replace(/{#ptag#}/g,ptag));}
$id("viewedList").innerHTML=html.join("");}},errorback:function(errCode){$empty();}});};PP.wg.buy.favored=function(){var that=this;if($isLogin()){$loadScript({id:"favored",url:"http://my.paipai.com/cgi-bin/favorite_new/GetFavItemJsonp?sizeperpage="+that.size+"&t="+Math.random(),callbackName:"FavoriteComdyListCallBack",callback:function(obj){if(obj.errCode==0&&obj.favoLists.length>0){var html=[],tpl='<li class="product"><a class=”url“ href="{#itemUrl#}?PTAG={#ptag#}" target="_blank"><img class="photo" src="{#imageUrl#}" alt=""></a><p class="price_wrap"> <span class="price">&yen;{#price#}</span></p><p class="fn_wrap"><a href="{#itemUrl#}?PTAG={#ptag#}" target="_blank" title="{#title#}">{#title#}</a></p></li>';for(var i=0,len=obj.favoLists.length;i<len;i++){var _item=obj.favoLists[i];if(!_item||_item.ItemLogo==""){continue;}
var pic=_item.ItemLogo.replace(/(jpg|gif)\.\d\.(jpg|gif)/,"120x120.jpg");html.push(tpl.replace(/{#title#}/g,_item.ItemNam).replace(/{#itemid#}/g,_item.ItemId).replace(/{#itemUrl#}/g,_item.ItemUrl||'http://auction1.paipai.com/'+_item.ItemId+'?PTAG={#ptag#}').replace(/{#imageUrl#}/g,pic).replace(/{#price#}/g,_item.Price).replace(/{#ptag#}/g,that.fptag+(i%6+1)));}
$id("favoredList").innerHTML=$xss(html.join(""),"none");$autoLoadImages();}else{hide();}},errorback:function(errCode){hide();}});}else{hide();}
function hide(){var favoredLi=$id("favoredLi");favoredLi.parentNode.removeChild(favoredLi);var favoredDiv=$id("favoredDiv");favoredDiv.parentNode.removeChild(favoredDiv);}}
PP.wg.buy.express=function(){var that=this;var params={"count":30,"offset":0,"searchtype":1,"adposcount":1,"commprice":'0|99999999'};var pnames=["pid","keyword","navid","metaid","siteid","count","offset","adposcount","commprice","local"];$each(pnames,function(v){params[v]=$getQuery(v);});var o={curPage:0,pageSize:6,autoHdisabled:false,url:"http://r.paipai.com/tws/express/ExpViewAd?"+$makeUrl(params)+'&t='+Math.random(),dom:$id("expressList")}
$loadScript({id:'express',url:o.url,isToken:true,timeout:2000,isAutoReport:true,reportOptions:{},reportType:'current',callbackName:'exp_search_callback',callback:function(obj){var items=obj[params["pid"]];if(obj.errCode==0&&items.length>0){if(params['pid']=='288231480781298991'||params['pid']=='432346668857154863'){for(var i=0,len=items.length;i<len;++i){items[i].image=$getImageUrlBySize(items[i].image,'120');}}
var ptag="";o.dom.innerHTML=$xss($formatJson("expressItemTpl",{arr:items}),"none");$autoLoadImages();that.scroll(items.length,that.size,that.wid,$id("express_prev"),$id("express_next"),$id("expressList"));$jq("#expressLi").show();var tempArr=[];for(var i=0;i<items.length;i++){tempArr.push(items[i].id);}
$loadScript("http://express.paipai.com/tws/expcomm/ExpViewAdStat?commid="+tempArr.join("|")+"&f=3&t="+(new Date).getTime());window['_express_adstat_callback']=function(obj){var itemList=obj["data"],priceDom,sellNumDom,item;for(var i=0,len=itemList.length;i<len;i++){item=itemList[i];priceDom=$id('expPrice'+item.commId);sellNumDom=$id('expSellNum'+item.commId);if(priceDom&&(parseFloat(priceDom.getAttribute('data-price'))>parseFloat(item.price))){priceDom.innerHTML=item.price;}
if(sellNumDom){sellNumDom.innerHTML=itemList[i]?"最近成交"+itemList[i]["payCnt"]+"笔":"";sellNumDom.style.display='block';}}}}else{var expressLi=$id("expressLi");expressLi.parentNode.removeChild(expressLi);var expressDiv=$id("expressDiv");expressDiv.parentNode.removeChild(expressDiv);PP.wg.buy.tabchange();}},errorback:function(errCode){}});that.setExpressLinks();};PP.wg.buy.scroll=function(tot,size,sw,prev,next,container){var that=this,sWidth=sw||400,cur=0,totPage=Math.ceil(tot/size),flag=false;container.style.position="absolute";if(totPage>1){$delClass(next,"arrow_right_disabled");}
prev.onclick=function(){if(cur==0||flag)return;flag=true;cur--;$delClass(next,"arrow_right_disabled");if(cur==0){$addClass(prev,"arrow_left_disabled");}
$animation(container,{"left":"+="+sWidth},{speed:500,onComplete:function(){flag=false;}});};next.onclick=function(){if(cur==totPage-1||flag)return;flag=true;cur++;$delClass(prev,"arrow_left_disabled");if(cur==totPage-1){$addClass(next,"arrow_right_disabled");}
$animation(container,{"left":"-="+sWidth},{speed:500,onComplete:function(){flag=false;}});};};PP.wg.buy.autoscroll=function(dom,tc){var that=this,ac=0;that.autoScrollInterval=setInterval(function(){if(ac<tc){$fireEvent(dom);ac++;}else{clearInterval(that.autoScrollInterval);}},5000);};PP.wg.buy.setscroll=function(){var that=this;$mouseover(that.contdom,function(oThis){clearInterval(that.autoScrollInterval);});};PP.wg.buy.setExpressLinks=function(opt){var links=$id("expressTag").getElementsByTagName("A");$each(links,function(v){if(v.getAttribute('datakeyword')){v.href+=("&keyword="+encodeURIComponent(v.getAttribute('datakeyword')||''));}})};
window['PP.wg.buy']='21393:20150402:20150402111944';
window['PP.wg.buy.time'] && window['PP.wg.buy.time'].push(new Date());/*  |xGv00|28ac139242651ebe481118833983f39d */